### ISSUE TITLE
Add support for streams

### ISSUE THREAD

**Issue by DarkSunsetLove** [kkevinm/iTunes-Discord-RP#24]
Hello,

Sometimes I listen to radio station streams in iTunes. However, iTunes RP for Discord doesn't recognize them, even when the song and artist name is showing. I would really like for my friends to see what I'm listening to, so adding support for radio streams would be greatly appreciated. Thanks!

**Comment by kevinmussi** [comment]
Hey, what version are you using? Because this issue should've been fixed since version 1.3.1, unless I missed something.
