### ISSUE TITLE
Add to homebrew 

### ISSUE THREAD

**Issue by daniel-white** [kkevinm/iTunes-Discord-RP#26]
It would be great if I could install this via home brew.

**Comment by kevinmussi** [comment]
That's a nice idea, actually, and it'd make it easier for people to update it. I'll look into adding it as a cask.

**Comment by PythonCoderAS** [comment]
You could also make the Cask on this repo, and tap the repo. That way, we wouldn't have to deal with the official requirements.

**Comment by kkevinm** [comment]
> You could also make the Cask on this repo, and tap the repo. That way, we wouldn't have to deal with the official requirements.

Thanks for that suggestion, I hadn't thought of that.

Anyway, it's now possible to install the app through `brew cask`. See [here](https://github.com/kkevinm/iTunes-Discord-RP#homebrew).
