### ISSUE TITLE
[Enhancement & Bug Fixes] Time Elapsed Bug

### ISSUE THREAD

**Issue by Kentakoong** [kkevinm/iTunes-Discord-RP#36]
![Screen Shot 2020-08-18 at 8 28 59 PM](https://user-images.githubusercontent.com/35761701/90519099-cd5aaa00-e191-11ea-8abb-baa5194db90a.png)

**Comment by Kentakoong** [comment]
The timestamp isn't in sync with the song somehow, it's some bugs with the software I think
Just for reporting, no concerns

**Comment by Kentakoong** [comment]
But when I re-opened the app it is fixed 👍🏻
For Enhancement

**Comment by Kentakoong** [comment]
For Normal Uses, fyi only. It's delayed by about 0.5-1 Secs
It's ok btw, no complaints

**Comment by kkevinm** [comment]
There was a bug in earlier versions where skipping ahead in the song would desync it, but it should work fine when using the most recent one. As for the small delay, it's normal.

**Comment by Kentakoong** [comment]
> There was a bug in earlier versions where skipping ahead in the song would desync it, but it should work fine when using the most recent one. As for the small delay, it's normal.

I didn't skip tho? so what's up

**Comment by Kentakoong** [comment]
by the way, I found out when I closed the app with the quit button (red one) and the song is like stopped on discord, the status 
![8D0B610C-41FE-4C5D-A62E-5A451DA0416C](https://user-images.githubusercontent.com/35761701/90527581-e5372b80-e19b-11ea-9023-492dd8ceb865.png)

**Comment by kkevinm** [comment]
If you're on the most recent version the app runs in the background when you use the red button, to quit it use CMD+Q.

**Comment by Kentakoong** [comment]
> If you're on the most recent version the app runs in the background when you use the red button, to quit it use CMD+Q.

No no, I meant i clicked the red button and it won't run in the background, I don't know why. But when i uses it after time like 15 mins it stopped responding.

**Comment by kkevinm** [comment]
What version are you using?

**Comment by Kentakoong** [comment]
> What version are you using?

The latest one!

**Comment by kkevinm** [comment]
Mh okay, I don't know what's happening to you, it works fine for me.

**Comment by Kentakoong** [comment]
I think it's ok tho. It's not that much of a problem, thanks
