### ISSUE TITLE
(Request): Can we get more rich presense features?

### ISSUE THREAD

**Issue by rohilpatel1** [kkevinm/iTunes-Discord-RP#39]
Hey, can we get a different color background for the music icon? And then also im getting a delay issue, and when i pause music, im still seeing elapsed time going up. 

Then can we get "Listening to Music" instead of "Playing Music"?

I am on macOS!

Thank you!

**Comment by rohilpatel1** [comment]
also add autoconnect

**Comment by undrgnd33** [comment]
I think it'd be pretty cool if we could have the album cover show instead of the itunes logo, but I don't know how hard that would be to implement

**Comment by Kentakoong** [comment]
> I think it'd be pretty cool if we could have the album cover show instead of the itunes logo, but I don't know how hard that would be to implement

ahhhh yes
an good idea. I would love that if you can do

**Comment by kkevinm** [comment]
> I think it'd be pretty cool if we could have the album cover show instead of the itunes logo, but I don't know how hard that would be to implement

That's impossible to do, because the Discord API just doesn't allow it. It's been brought up multiple times already so I'll also add it in the readme, I guess.

**Comment by kkevinm** [comment]
Also, I'll close this since everything you asked either was already fixed or can't be done:
- Music icon: you can choose different icons with different colors.
- Delay issue: should be fixed in latest version. If you still experience some errors, turn off AppNap (it's explained [here](https://github.com/kkevinm/iTunes-Discord-RP/issues/38#issuecomment-683988051)).
- "Listening to Music": if it's possible, I couldn't find a way to do it.
- Autoconnect: already there, just tick the checkbox before connecting.

**Comment by rohilpatel1** [comment]
It is possible to do the music cover art. You just need to save the image to the server

**Comment by rohilpatel1** [comment]
Also I meant the iOS 14 music icon, not the iOS 8 one.

**Comment by kkevinm** [comment]
> It is possible to do the music cover art. You just need to save the image to the server
Discord doesn't let you do that. You can only use the images that you upload beforehand in the application assets.

**Comment by Kentakoong** [comment]
> > It is possible to do the music cover art. You just need to save the image to the server.
> 
> 
> 
> Discord doesn't let you do that. You can only use the images that you upload beforehand in the application assets.

Dang, that's a shame

**Comment by rohilpatel1** [comment]
> > It is possible to do the music cover art. You just need to save the image to the server.
> 
> Discord doesn't let you do that. You can only use the images that you upload beforehand in the application assets.

Oh yeah ur right. Imma make my version better optimized for Big Sur if you won't do it lol
