### ISSUE TITLE
Could you change the RP Type from "Playing A Game" to "Listening To"?

### ISSUE THREAD

**Issue by penguid369** [kkevinm/iTunes-Discord-RP#41]
It's not really a bug but rather a small 'context issue'.

**Comment by kkevinm** [comment]
This has already been addressed and, to my knowledge, it's currently not possible using the standard Rich Presence API (apps like Spotify or Twitch use custom integrations).

**Comment by Kentakoong** [comment]
But, like. Can you try do like an custom API for it, or it's impossible.

**Comment by Kentakoong** [comment]
![A61E5E03-8A3D-4AA5-971C-E8FCF6B06373](https://user-images.githubusercontent.com/35761701/94342076-b5036800-0038-11eb-896f-cd52e7b59ff1.png)
@kkevinm but how did these bots did it?
Custom APIs?

**Comment by kkevinm** [comment]
What I meant is that it's not possible with the Rich Presence API, for whatever reason, but possible using the more general Discord API. So yeah, that could be changed, but no guarantees for now.

**Comment by penguid369** [comment]
OK then.

**Comment by Kentakoong** [comment]
> What I meant is that it's not possible with the Rich Presence API, for whatever reason, but possible using the more general Discord API. So yeah, that could be changed, but no guarantees for now.

Oh okay
